### ISSUE TITLE
$content_width not set correctly for the slider

### ISSUE THREAD

**Issue by pjrobertson** [puikinsh/Sparkling#118]
It seems a recent change in Jetpack/Wordpress 4.4 means that slider images no longer display correctly. 

A filter in the Jetpack plugin (see below) means that the max width of any image is 648px for a normal page. This is the value set in the `sizes` attribute of the slider image (from code in wp-includes/media.php) and the max slider image is 648px.

See smartairfilters.com/cn/ for an example of this.

To reproduce:
- Install WP 4.4, Jetpack plugin, Sparkling
- Add a slider post and featured image
- View the homepage

```
//Jetpack plugin class.jetpack.php
        public static function get_content_width() {
                $content_width = isset( $GLOBALS['content_width'] ) ? $GLOBALS['content_width'] : false;
                /**
                 * Filter the Content Width value.
                 *
                 * @since 2.2.3
                 *
                 * @param string $content_width Content Width value.
                 */
                return apply_filters( 'jetpack_content_width', $content_width );
        }
```

**Comment by FreeWPTP** [comment]
I followed the instructions that you have shared above but could not reproduce the issue. The slider is working fine displaying full  width images.

It seems it is also displaying fine on your shared site.

Please advise.

**Comment by pjrobertson** [comment]
Hi, it's been a while but here are my thoughts (from what I can remember)...

Did you install the Jetpack plugin and enable the image CDN/optimisation option? (I can't remember the exact option right now, but it was an option that after being enabled meant images were mirrored from the wordpress CDN).
I think that was what was causing this problem. I've since disabled the Jetpack plugin on our shared site and the problem went away.

**Comment by giucu91** [comment]
I think the issue here is the same with this one : https://github.com/puikinsh/Activello/issues/81
