### ISSUE TITLE
Change screen reader text h1 tag for SEO purpose

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#119]
Change screen reader text h1 tag added by following code.

`<h1 class=”screen-reader-text”>Post navigation</h1>`

Related topics :

https://colorlib.com/wp/forums/topic/multiple-h1-headings/
https://colorlib.com/wp/forums/topic/multiple-h1-headings-on-post-page/

**Comment by mcmichels** [comment]
Do you really want to change this in every case to H6 as you mentioned in the support forum? If yes let me know, i will implement this.

**Comment by FreeWPTP** [comment]
It is already changed in the theme so closing this topic.
