### ISSUE TITLE
Sparkling Popular Posts not working. Please Help?

### ISSUE THREAD

**Issue by anirudhpulikonda** [puikinsh/Sparkling#120]
Hi Guys

I'm using Sparkling Popular posts widget in my blog. But the posts seeing in the widget are not relevant to High Traffic post.

It's shows only posts which have high comments on it. Please help to change it to view count

My blog URL : [https://www.watchmetech.com](url)

**Comment by puikinsh** [comment]
For theme support related questions please use our support forum: https://colorlib.com/wp/forums/

Create your own support thread and we will help you from there.

Github is for bug reporting and this is not a bug.
