### ISSUE TITLE
Feature Request - Popular Posts widget should display default image for the post if no image is set

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#122]
Related Topic :

https://colorlib.com/wp/forums/topic/default-thumbnail-for-popular-posts/

**Comment by cristianraiber** [comment]
Note: users want to be able to specify a default image to be used as a placeholder, when the related post doesn't have a featured image. 

cc @giucu91

**Comment by cristianraiber** [comment]
@giucu91 - media uploader isn't working.
