### ISSUE TITLE
Use larger post image for full-width posts

### ISSUE THREAD

**Issue by escoand** [puikinsh/Sparkling#124]
The theme always uses a 750x410 image as post image.
For full-width posts the better size would be 1140×624.

**Comment by lutrov** [comment]
This should be an easy fix, by inclusion of the following under the "media" section in the main stylesheet:

    .single-featured {
    	width: 100%;
    	height: auto;
    }

I have tested it with my child theme and it works well, including mobile devices.

**Comment by escoand** [comment]
But this only upscales the smaller image. Ich can create a pullrequest if you want.

**Comment by lutrov** [comment]
That's it what it's supposed to do. It also downscales a larger image.
