### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by Angristan** [puikinsh/Sparkling#125]
Hello,

This part is not translated in french.

![screenshot_25-10-2016_b ywabpddj](https://cloud.githubusercontent.com/assets/11699655/19690657/af403afe-9ad1-11e6-8fa4-a66ddfefbcd2.png)

**Comment by mcmichels** [comment]
@Angristan what should it named in french?

**Comment by Angristan** [comment]
It depends.

"Anciens posts" or "Anciens articles" or "Suivant"

**Comment by mcmichels** [comment]
I cannot decide, i don't speak french. What do you think fits best?

**Comment by Angristan** [comment]
"Articles précédents" seems good.

**Comment by FreeWPTP** [comment]
The translations of theme are done by contributors whom we list on our site here https://colorlib.com/wp/contributors/

You can help us to translate it in the french on the following site

https://translate.wordpress.org/projects/wp-themes/sparkling/fr/default

Or translate it for yourself as described on the following pages.

https://premium.wpmudev.org/blog/how-to-translate-a-wordpress-theme/

http://www.themeum.com/how-to-translate-a-wordpress-theme-with-poedit/

**Comment by cristianraiber** [comment]
Closing this as it's not a theme related issue.
