### ISSUE TITLE
All buttons have btn-default class - Please fix.

### ISSUE THREAD

**Issue by skeathy** [puikinsh/Sparkling#127]
Please edit the **functions.js** file as it is too broad and adds the .btn-default class to most buttons when not needed:

jQuery('#submit, button[type=submit], html input[type=button], input[type=reset], input[type=submit]').addClass('btn btn-default');

Note that In most cases I'd just edit your theme but I'm using a child theme, so it is a little off.

Thanks. #

**Comment by FreeWPTP** [comment]
Actually it adds the class 'btn btn-default' to the buttons to apply Bootstrap styling to them but if we remove this code then it will affect thousands of sites using Sparkling theme.

Instead if you let us know the problem you are having with it on our following forum then we would be more than happy to help you.

https://colorlib.com/wp/forums/forum/sparkling/

**Comment by skeathy** [comment]
That code assumes that everyone wants to use 'btn btn-default' for every button - crazy town.  What if I have a case where I need a different Bootstrap button style:
.btn-primary
.btn-success
.btn-info
.btn-warning
.btn-danger
.btn-link

Sure add '.btn' class, but I'd rather you didn't make personal styling assumptions for every button on our sites.

**Comment by FreeWPTP** [comment]
If you have to use different style then you have to add respective classes to the buttons so in that case just remove the default class. The changes are not made on your site but in the theme that you are using on your site by accepting how the theme is working.

**Comment by skeathy** [comment]
Ideally that is how it should work I'd just add 'btn-success' or other classes as needed. However the JavaScript is adding 'btn-default' to all the buttons on the site in the **functions.js** file:

jQuery('#submit, button[type=submit], html **input[type=button]**, input[type=reset], input[type=submit]').addClass('**btn btn-default**');

Not sure if I'm making it clear that adding **input[type=button]** globally to every button on the site is causing issues.

**Comment by FreeWPTP** [comment]
Yes i agree with you but as said previously if we remove this code then it will affect thousands of sites using Sparkling theme.

So the easiest solution is to remove this default class when you add any other class to the buttons. We can remove this class using simple JS code or change the style using CSS code.

We can also remove this specifically for you but not for all users.

If you need any help regarding this then feel free to ask it in our following sparkling theme forum.

https://colorlib.com/wp/forums/forum/sparkling/

**Comment by skeathy** [comment]
OK, I understand your situation.  Kinda weird but I'll just add this to my child theme: jQuery('.btn-success, .btn-primary, .btn-danger, .btn-link').removeClass('btn-default')
