### ISSUE TITLE
Missing closing div for .main-content-inner in footer.php

### ISSUE THREAD

**Issue by lutrov** [puikinsh/Sparkling#129]
The `footer.php` file is missing a closing div for the .main-content-inner class.

Before this line:

`</div><!-- close .row -->`

There should be this line:

`</div><!-- close .main-content-inner -->`

**Comment by lutrov** [comment]
I have attached what I think the new `footer.php` should look like.

[new.txt](https://github.com/puikinsh/Sparkling/files/565898/new.txt)

**Comment by FreeWPTP** [comment]
Actually it is closed in the sidebar.php file but let's close it in the page-fullwidth.php file of theme.
