### ISSUE TITLE
In INDEX home not show the TITLE second Post?

### ISSUE THREAD

**Issue by enlacee** [puikinsh/Sparkling#14]
I'm review code and 
style.cs: 446

    .blog .format-aside .entry-title,
    .archive .format-aside .entry-title {
    /*display: none;*/}

I'm commnet but (THIS CODE IS USEFULL?) 

![image mi wordpress](http://i57.tinypic.com/14bn4lh.png)

**Comment by puikinsh** [comment]
Please read more information about WordPress post formats that you can [find here](http://codex.wordpress.org/Post_Formats). If you are not using Aside Post Format then this code is not going to do anything.

**Comment by enlacee** [comment]
ohm! it's correct. I'm reading
