### ISSUE TITLE
Add option to change background color

### ISSUE THREAD

**Issue by eudoxos** [puikinsh/Sparkling#140]
I would like to use sparkling as dark theme, by setting text color to light/white. I don't see the option to change background color anywhere. Since the theme allows to change most other colors (both in header and footer), background color should also be settable. Thanks!

**Comment by puikinsh** [comment]
For theme support related questions please use our support forum: https://colorlib.com/wp/forums/
Create your own support thread and we will help you from there.

Github is for issue/bug/error tracking.
