### ISSUE TITLE
Read more button should be displayed when the <!--more--> tag is used in the post

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#142]
Read more button should be displayed when the  tag is used in the post and the full post content is displayed on the blog page.

Related Topic :

https://colorlib.com/wp/forums/topic/no-read-more-button-2/
https://colorlib.com/wp/forums/topic/difficulty-with-read-more-summary-at-the-end-of-a-new-post/
https://colorlib.com/wp/forums/topic/read-more-tag-doesent-work/

**Comment by AnaMaican** [comment]
@giucu91 It seems that the customizer uses the_excerpt function and in the front end, the_content function.
