### ISSUE TITLE
Previous/Next page pagination pointing to incorrect links

### ISSUE THREAD

**Issue by slobjones** [puikinsh/Sparkling#143]
Previous post and next post links are skipping WordPress posts with the Sparkling theme.

This occurs randomly. When I change to any of the default WordPress themes, the problem goes away. Disabling plugins, as suggested on the Colorlib support forum, does nothing. This is undeniably an issue with the Sparkling theme.

Sparkling developers must address this issue. The most recent update also introduced pagination issues on archive pages, which I understand they're addressing in the next theme update. I ask that the developers address and fix previous/next page post pagination as well.

**Comment by slobjones** [comment]
To update, rolling back to Sparkling version 2.2.2 solves the previous/next pagination issue. 

This further indicates the pagination issue first appeared in 2.3.2.

**Comment by giucu91** [comment]
Hello @slobjones,

This is not a bug, the next/prev links skip some posts because they will show only posts that are in the same category with the current article.

Hope that helps.

Thank you,
George.

**Comment by slobjones** [comment]
So, let me get this straight, George. You purposely designed the update, Sparkling 2.3.2, so when the viewer displays ALL articles and expects prev/next to scroll chronologically through ALL articles, the theme only displays articles in a particular category.

This is counter-intuitive and defies the logic that WordPress demands. In fact, I'm sure it violates the minimal standards that WordPress defines as acceptable to include a theme in its listings.

I do appreciate your reply, but you're way out of line with this design choice, and I would expect you to correct it.

**Comment by cristianraiber** [comment]
@slobjones - George might not have phrased this perfectly. 

You're right about the fact that this is a bug, and it will be addressed via an update, in the upcoming version of the theme. This was not George's fault, as that particular piece of code was implemented by another developer that worked on the theme before he took on the project.

While we love getting feedback on our work, assumptions such as this one: 

``` In fact, I'm sure it violates the minimal standards that WordPress defines as acceptable to include a theme in its listings.```
