### ISSUE TITLE
Fluid and sidebar width changes

### ISSUE THREAD

**Issue by avibrazil** [puikinsh/Sparkling#147]
Quick question: is there a GUI way to change it to fluid width and reduce the width of sidebar in favor of larger main content ?

Or I'll have to fork it and change it in the code (container ➡ container-fluid & col-md-8 ➡ col-md-9)? I'm fine with changing it in the code. I just want to make sure this is right path for me.

If there is no GUI way to do that, I'd suggest it as a new feature.

Thank you for such a beautiful and functional theme.

**Comment by giucu91** [comment]
Hello @avibrazil,

The right way to do this is to create a child theme and override the right files in order to do that.

Thank you,
Geroge.

**Comment by avibrazil** [comment]
Yes, thats what I did. Thank you
