### ISSUE TITLE
Security- username displays when hovering authors posts

### ISSUE THREAD

**Issue by ghost** [puikinsh/Sparkling#15]
Hi there, 

Not sure if this is a issue with the theme or wordpress.

When you hover over the authors name the hyper-link in the bottom left hand corner reveals the authors username.

In user settings I have changed the users first, last and nickname to different words and the Display name publicly to something different.

I've also tried adding a new user then deleting the original users account.

I am using another theme (RokoPhoto) on a different blog, when hovering the author the url displays the Display Name. 
![slice 1](https://cloud.githubusercontent.com/assets/7758624/6440471/27aad720-c0d5-11e4-81a5-3419887d1cf0.png)

**Comment by puikinsh** [comment]
Your mentioned theme uses [the_author_posts_link](http://codex.wordpress.org/Function_Reference/the_author_posts_link) and Sparkling theme uses [get_author_posts_url](http://codex.wordpress.org/Function_Reference/get_author_posts_url). Why? We are using it outside loop, so we need to get user based on its ID. 

The same code is also part of [Underscore theme](https://github.com/Automattic/_s/blob/master/inc/template-tags.php#L90-L93) that you can see here and we have no plans on changing it as I don't think it might cause any problems with website security. If you think that it might cause problems you can feel free to use other method to display posts from specific authors.
