### ISSUE TITLE
[Bug] Clicking level 1 dropdown menu on mobile

### ISSUE THREAD

**Issue by laranz** [puikinsh/Sparkling#151]
I have problems with clicking the level 1 links. In desktop view I can click on them, but when I view the website on a mobile phone, the level 1 links cannot be clicked. Instead, clicking on it reveals the level 2 items. How can I make the level 1 links clickable on mobile, but clicking the down arrow (or the space to the right of the down arrow) reveals the level 2 items?

Reported ON: https://colorlib.com/wp/forums/topic/clicking-level-1-dropdown-menu-on-mobile/#post-94024

**Comment by cristianraiber** [comment]
@giucu91 - please see this

**Comment by cristianraiber** [comment]
@giucu91 - this still doesn't seem to be working for 2nd & 3rd level drop-down menus. Clicking on the little drop-down arrow does nothing.
