### ISSUE TITLE
What's this MT_Notify_System ? Slow as hell!

### ISSUE THREAD

**Issue by 7starsone** [puikinsh/Sparkling#156]
Hello,
that's incredible...
why do you set something like this?

![Slow Query one](http://i63.tinypic.com/72adtz.jpg)
![Slow Query 2](http://i64.tinypic.com/vopmht.jpg)
![Slow Query 3](http://i68.tinypic.com/2zg7rpv.jpg)

more than 20 secs to any admin page...

please, or you fix it once for all or delete this unuseful routine...
thank you very much

**Comment by 7starsone** [comment]
absolutely had to...

```
//Include Welcome Screen
//require get_template_directory() . '/inc/welcome-screen/welcome-page-setup.php';
```
and now normal as usual, not even 1 sec...

get rid of it, please... 27 secs aren't acceptable at all
how is possible that you didn't test this properly? Maybe is the union between this and W3TC the issue?

thanks

**Comment by cristianraiber** [comment]
HI @7starsone - this is actually very strange. It's not slowing down the sites for us in any way. Do you think you could provide me with access to your site so I can see what's going on? We currently have this system deployed on well over 5,000 websites and no one's reported anything like this.

**Comment by 7starsone** [comment]
@cristianraiber  "abandoned project" ? Are you sure? As I know it was updated 2 weeks ago...

anyway, if you want let me know where's the problem...honestly I have no time to deeply study the code.
Indeed, this happened when updated the theme....
thank you, best regards

**Comment by cristianraiber** [comment]
@7starsone - where did you update the theme from? Latest version on w.org is different from the one (development) currently on GitHub (here). 

- yes, look at W3TC number of solved replies in last 2 months; 8/164.

**Comment by 7starsone** [comment]
downloaded it here...Sparkling-master

**Comment by cristianraiber** [comment]
That's the reason why. This is a development version, currently unreleased to the public. If you'd go ahead and use the w.org one, that doesn't have this issue :)

**Comment by 7starsone** [comment]
but enough to replace the welcome-page-setup.php OR... ?

**Comment by cristianraiber** [comment]
@7starsone - you'd be safer just using the one from w.org. This is not (yet) fully tested code available here, since it's undergoing development. 

Mind you - we'll make sure to fix that problem in welcome-page-setup.php with the next release.

**Comment by 7starsone** [comment]
also, maybe found other... it seems that the page navigation is broken... (css only?)

look at this 
![page navi](http://i67.tinypic.com/2rr4e0x.jpg)

is this the usual navi?
thanks
