### ISSUE TITLE
Typography issue - needs to be addressed. 

### ISSUE THREAD

**Issue by cristianraiber** [puikinsh/Sparkling#157]
@puikinsh - we've started working on creating that front-page enhancement for Sparkling. However, the theme's current typography isn't creating the best result - just FYI. 

cc @ngabyn

**Comment by puikinsh** [comment]
Those settings are completely dated, that's true.

**Comment by cristianraiber** [comment]
Closing this until MedZone theme is launched, with latest framework. It'll be better than what Shapely is doing now.
