### ISSUE TITLE
Element color on hover issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#162]
The title element in the slider has no hover, when it's a link.

![image](https://user-images.githubusercontent.com/23457094/26843148-ebd4ab86-4af7-11e7-8842-b7141bb780a6.png)

**Comment by cristianraiber** [comment]
@giucu91 - this still doesn't seem to work as intended. 

Below file is a customizer export (JSON) format that can be re-imported using this plugin: https://wordpress.org/plugins/customizer-export-import/. 

:fire: :fire: Before trying to import the file, change it's extension to `.dat`. GitHub doesn't allow uploading `.dat` files.


[Sparkling-export.txt](https://github.com/puikinsh/Sparkling/files/1217786/Sparkling-export.txt)
