### ISSUE TITLE
Tagline issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#164]
The tagline doesn't appear.

![image](https://user-images.githubusercontent.com/23457094/26869831-7eddb9e4-4b76-11e7-889d-e480cc4e3765.png)

**Comment by giucu91** [comment]
@c0sm1n87 , @cristianraiber How will we proceed here? Because Sparkling never showed the tagline and I think all our users have checked "Display Site title and Tagline". If we add the tagline all the blogs will display it and it messes up the layout if they have long taglines.

**Comment by cristianraiber** [comment]
Closing this as it's not possible to implement it without risking to break a couple thousand websites.

**Comment by mhagnumdw** [comment]
@giucu91 , @cristianraiber 
Can you provide the code snippet that displays the tagline? So whoever wants can change by itself.

**Comment by cristianraiber** [comment]
@mhagnumdw - this is a question better fit for the Colorlib support forums. In here, we only handle bugs and features.
