### ISSUE TITLE
Customizing Primary menu - issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#169]
When I change the color of "Top nav item hover color", the color of the custom links in the menu, also changes.

![image](https://user-images.githubusercontent.com/23457094/26887046-a7a1510e-4baf-11e7-9b28-44ae4e074e23.png)

**Comment by giucu91** [comment]
This happens when you have the home page twice in menu and you're on the home page.

**Comment by cristianraiber** [comment]
This wasn't actually a bug.
