### ISSUE TITLE
Bad formatting with Events Manager plugin

### ISSUE THREAD

**Issue by Nio01** [puikinsh/Sparkling#17]
If you use the events manager plugin, create an event with at least 2 booking tickets and open the event page on website, the tickets table isn't formatted well.

![screen01](https://cloud.githubusercontent.com/assets/7456968/7338727/8937f062-ec55-11e4-88b4-c3838410249e.png)

EDIT:
Actually the error isn't relative to Events Manager. EACH table is poorly formatted.
Try to add a sample html table in a page.

**Comment by puikinsh** [comment]
Do you have a live example of this that I can see and test right away? 

It would be faster than trying to replicate this on my demo.

**Comment by Nio01** [comment]
Sure:
http://federicomatera.altervista.org/resume/events/5-castelli-half-marathon/

**Comment by Nio01** [comment]
I noticed that in mobile version even the event map is poorly formatted.

**Comment by Nio01** [comment]
Actually the error isn't relative to Events Manager. EACH table is poorly formatted.
Try to add a sample html table in a page.

**Comment by puikinsh** [comment]
Regular HTML tables are formatted fine as you can see it on [theme demo](http://colorlib.com/sparkling/about/page-markup-and-formatting/). 

Markup for table looks like this: 

```
<table>
<tbody>
<tr>
<th>Employee</th>
<th class="views">Salary</th>
<th></th>
</tr>
<tr class="odd">
<td><a href="http://example.com/">Jane</a></td>
<td>$1</td>
<td>Because that's all Steve Job' needed for a salary.</td>
</tr>
<tr class="even">
<td><a href="http://example.com">John</a></td>
<td>$100K</td>
<td>For all the blogging he does.</td>
</tr>
<tr class="odd">
<td><a href="http://example.com/">Jane</a></td>
<td>$100M</td>
<td>Pictures are worth a thousand words, right? So Tom x 1,000.</td>
</tr>
<tr class="even">
<td><a href="http://example.com/">Jane</a></td>
<td>$100B</td>
<td>With hair like that?! Enough said...</td>
</tr>
</tbody>
</table>
```

On output there is a Bootstrap calls applied to it to make it look and work nicely.
