### ISSUE TITLE
Customizing - footer menu/links issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#170]
Footer menu links should show in a line, not taking into account any drop-down hierarchy established by the user, in the back-end. This is more of a "decide for the user" situation. This is applicable `only` for the "Footer Links Menu"

---

![image](https://user-images.githubusercontent.com/23457094/26887515-ded38b78-4bb0-11e7-9e01-7c2273da83a6.png)

**Comment by cristianraiber** [comment]
@giucu91 - this isn't working as intended. If you look at the attached screenshot, there's two second level menus that are missing from the front-end output. The logic here was that we'll be showing all menu items, no matter the hierarchy (if it's a drop-down or not). You're currently not outputting second-level menu items. 

---

![image](https://user-images.githubusercontent.com/7841556/29212158-aff653ee-7ea5-11e7-8dc6-c2f3ff23e7c9.png)
