### ISSUE TITLE
Sparkling popular posts and Sparkling social widget issue - footer widgets

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#174]
### The Sparkling social widget doesn't appear below the other widget.

![image](https://user-images.githubusercontent.com/23457094/26936400-4a013dac-4c77-11e7-8a13-2f4e794f94fd.png)

**Comment by cristianraiber** [comment]
@giucu91 - footer "follow us" widget icons should be left aligned. Currently, they're center aligned. 

- Sparkling social widget: *left aligned*
- Below footer social icons: *center aligned*

---


![image](https://user-images.githubusercontent.com/7841556/29212044-3800e610-7ea5-11e7-8ddd-989590dc749a.png)
