### ISSUE TITLE
Custom Menu  - footer widget issue

### ISSUE THREAD

**Issue by AnaMaican** [puikinsh/Sparkling#176]
Lines do not appear where they should be.

![image](https://user-images.githubusercontent.com/23457094/26937194-6b249018-4c79-11e7-8dae-3d259da13538.png)

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/29211889-601a69e2-7ea4-11e7-8f82-676fec783294.png)

---

This is just for reference purposes. While you might think the whole menu layout should be boxed, this is the current CSS styling the theme offers. IMHO, it doesn't look bad.
