### ISSUE TITLE
Allow both Fontawesome and Glyphicons in menu

### ISSUE THREAD

**Issue by mattzuba** [puikinsh/Sparkling#18]
Since Sparkling ships with FA as well, should be pretty easy to check the menu item attr to see if it starts with fa- or glyphicon- and use the appropriate base class.  If FontAwesome is in use, I'd recommend using the fixed width class as well.

**Comment by puikinsh** [comment]
You can already use FontAwesome icons by adding them directly inside "Navigation Label" field. 

So the navigation label would look something like this 

```
<i class="fa fa-cogs"></i> About us
```

**Comment by mattzuba** [comment]
Ah, I didn't think about that.  I added the classes to the attribute and then used some CSS to remove what glyphicons adds.  If you want to still implement 'fa' detection, feel free to keep this open, otherwise you can close it out.  Thanks!

**Comment by puikinsh** [comment]
I think that I should mention this solution in documentation, so will keep it open for now.

**Comment by puikinsh** [comment]
I have now references this in [theme documentation](https://colorlib.com/wp/support/sparkling/) therefore I am closing this issue.
