### ISSUE TITLE
Does Sparkling Ready for AMP?

### ISSUE THREAD

**Issue by emretalu** [puikinsh/Sparkling#182]
Hi,

I want to use your template one of my project. But I wonder does your template support AMP standarts? If not, when will it be ready for AMP?

Thanks,

**Comment by cristianraiber** [comment]
@emretalu - Sparkling doesn't currently offer support for AMP nor is it planned for the near future. Although, it shouldn't create problems when used in conjunction with the official WordPress AMP plugin.
