### ISSUE TITLE
Prioritize Visible Content

### ISSUE THREAD

**Issue by emretalu** [puikinsh/Sparkling#183]
Hi,

How can we fix the **prioritize visible content** warning on pagespeed for this template? When I used default wordpress template there were any issue about it. I thought that the reason of this issue is slider module, but when I removed it nothing has changed.

Can you please help me?
Thanks,

**Comment by cristianraiber** [comment]
@emretalu - please provide more details about this issue. Screenshots, would be really helpful or at least your site's URL.

**Comment by emretalu** [comment]
@cristianraiber here is my site's URL: https://blog.masterofproject.com/

I only use google pagespeed insights tool. You can check the warnings here:
https://developers.google.com/speed/pagespeed/insights/

Thanks,

**Comment by emretalu** [comment]
Finally, I found the solution.

The problem is about flexslider which is embedded this template. It loads after the DOM is ready. That's because Google Pagespeed throw that kind of error.

And one another reason is the lazy load plugin that I'm using. I excluded the first post's image class and the problem was solved.

Thanks anyway,
