### ISSUE TITLE
Menus alignment

### ISSUE THREAD

**Issue by ornatwork** [puikinsh/Sparkling#184]
Is there a way to align the main menu all the way to the left.  To align up with the box that holds the content of the page ? ( The header image aligns with the box )

**Comment by cristianraiber** [comment]
@ornatwork - could you please help us out with your site URL ? 

cc @vinoddalvi

**Comment by vinoddalvi** [comment]
@ornatwork You can achieve this by adding the following CSS code in the Custom CSS option of the latest version of Sparkling theme on the below path.

Admin Area -> Appearance -> Customize -> Additional CSS

```
@media (min-width: 768px){
#page .navbar-header {
    float: right;
}
#page .nav.navbar-nav {
    float: left;
}
}


```

If you have more questions then please ask it in our support forum here https://colorlib.com/wp/forums/forum/sparkling/

**Comment by cristianraiber** [comment]
Marking this as closed as it's not a theme related issue.
