### ISSUE TITLE
Safari Browser Image Load Problem

### ISSUE THREAD

**Issue by emretalu** [puikinsh/Sparkling#185]
Hi,

I have problems while opening my site with Safari browser. I cannot load images(especially logo image) while using this browser on mobile, but I don't have any problems with other mobile browsers. How can I solve this issue?

Thanks,

**Comment by emretalu** [comment]
Update:

This problem is not only for website logo, but also images that inside the post pages.
On AMP version I have only logo problem but when I changed it as Non-Amp View, all images not loading.

Here is my website's url: https://blog.masterofproject.com

Thanks for your help,

**Comment by giucu91** [comment]
Hello @emretalu,

Can you please deactivate the AMP plugin to see if this is causing the issue ?

Thank you,
George.

**Comment by emretalu** [comment]
Hi @giucu91 

I already test it but nothing has changed. In addition to that non-amp version I have same error.
As I understand, the problem is all about Safari browser.

**Comment by giucu91** [comment]
Hello @emretalu,

I tested https://colorlib.com/sparkling/ on an iPhone 7 and everything is OK. After that I tested your website and everything looks good there as well. Can you please clear the cache on your mobile phone and test it again?

Thank you,
George

**Comment by emretalu** [comment]
Hello @giucu91 ,

I checked my site with iPhone 6 with iOS 10.2 and 10.3.2 versions with Safari and Chrome browsers but still I have the same problem. I tried to deactivate AMP plugin but nothing changed.

After that I changed template and I don't have any problems with it. I don't know what is the reason of this problem.

**Comment by emretalu** [comment]
Hi @giucu91 ,

I solve the problem. The problem is all about server side. Somehow, the server corrupted images. Safari and also on Internet Explorer, I cannot show latest uploaded images. If you have any idea about it, please share with me. 

Otherwise, thanks for your attention.

**Comment by cristianraiber** [comment]
Marking this as closed as it's not theme related.
