### ISSUE TITLE
Firefox css problem in header

### ISSUE THREAD

**Issue by AlexandreBT** [puikinsh/Sparkling#196]
Hi,

A little CSS problem with firefox on the top menu:

![2017-08-18 12_32_09-sparkling - free flat design wordpress theme developed using bootstrap 3 and is](https://user-images.githubusercontent.com/206181/29455389-49b5f69a-8411-11e7-956b-b6174ed33b12.png)

No problem with Chrome: 

![2017-08-18 12_32_37-sparkling - free flat design wordpress theme developed using bootstrap 3 and is](https://user-images.githubusercontent.com/206181/29455409-57abcd24-8411-11e7-891f-45ebb761d637.png)

**Comment by giucu91** [comment]
Hello @AlexandreBT,

Can you please give me your website's URL ?

Thank you,
George.

**Comment by AlexandreBT** [comment]
Hi @giucu91 

It's the Sparkling demo page: https://colorlib.com/sparkling/

**Comment by cristianraiber** [comment]
@puikinsh - please update Sparkling on your demo instance to latest version (2.3.5) and clear CDN.
