### ISSUE TITLE
Header menu issues in latest theme version

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/Sparkling#197]
The dropdown menu caret icon is misplaced and second level sub menu is not displaying correctly in the latest version of theme.

You can see the issue on demo site https://colorlib.com/sparkling/

Related Topic:

https://colorlib.com/wp/forums/topic/header-issue/#post-113559

**Comment by cristianraiber** [comment]
@vinoddalvi - on demo, it's not latest version of the theme.

**Comment by vinoddalvi** [comment]
But i could reproduce the issue on my test site using latest version 2.3.5 of theme.

My test site is on localhost so i shared the demo site URL which displays same issue.

Could you please test it on your site?

**Comment by cristianraiber** [comment]
@giucu91 - please see this. 

@vinoddalvi - we did test it on our localhosts, there were no issues

**Comment by vinoddalvi** [comment]
Here's the screenshot from my test site.

![screenshot 9](https://user-images.githubusercontent.com/5412913/29459347-d389a7ac-8440-11e7-9844-b1a7348ce7ef.png)

Also more user are facing the issue. See here https://colorlib.com/wp/forums/topic/problem-after-update-do-2-3-5/

**Comment by cristianraiber** [comment]
Thank you @vinoddalvi . We're on it!

**Comment by cristianraiber** [comment]
@vinoddalvi - could you please tell me the steps you took ? it's fine for me: https://georgeciobanu.com/sparkling/

**Comment by vinoddalvi** [comment]
Sorry it was browser cache issue.
