### ISSUE TITLE
I can't use Bootstrap classes 

### ISSUE THREAD

**Issue by AlexandreBT** [puikinsh/Sparkling#198]
Hi,

Does Sparkling use a full version of Bootsrap ? Because I can't use Bootstrap classes directly in posts. Do you know why ? I don't want to use EBS Shortcode because It has not been updated for 2 years.

![2017-08-21 12_04_25-modifier l article t as pas 1 po _ wordpress](https://user-images.githubusercontent.com/206181/29514538-3739f46c-8669-11e7-85ea-2634c71e10b1.png)

![2017-08-21 12_05_05-t as pas 1 po _](https://user-images.githubusercontent.com/206181/29514539-3752643e-8669-11e7-85c9-fd05c284311b.png)

Sorry if I did not post to the right place, I did not know if I should post it here or on the Colorlib forum.

**Comment by giucu91** [comment]
Hello @AlexandreBT ,

Here are all the Bootstrap  classes : https://getbootstrap.com/docs/4.0/layout/grid/.

The "col" class is not a valid Bootstrap class.

Have a nice day,
George.

**Comment by AlexandreBT** [comment]
Oh yes, i'm tired...

Thanks you =)
