### ISSUE TITLE
After this update bootstrap butons not work

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/Sparkling#199]
Topic:

https://wordpress.org/support/topic/bootstrap-10/#post-9438491

**Comment by cristianraiber** [comment]
@giucu91 please see this

**Comment by cristianraiber** [comment]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/7841556/39584237-9624af6c-4efa-11e8-99e8-cc5f035ebdc2.png">

**Comment by cristianraiber** [comment]
The code I used: (same as the one provided by the user, just pasted here for reference):

```<div class="dropdown"><button id="dropdownMenu1" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
Download

</button>
<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
 	<li><a href="http://rlsbb.ru/">datafile-rapidgator</a></li>
</ul>
</div>```
