### ISSUE TITLE
Bad thumbnail in popular posts widget

### ISSUE THREAD

**Issue by qant** [puikinsh/Sparkling#20]
file to fix:  themedir/inc/widgets/widget-popular-posts.php

line: 
echo get_the_post_thumbnail(get_the_ID() , 'tab-small'); 
changet to:
echo get_the_post_thumbnail(get_the_ID() , 'thumbnail',array('class'	=> "img-resposive"));

**Comment by puikinsh** [comment]
`tab-small` is actually thumbnail ID inside `functions.php` to generate these 60px by 60px images. Your approach is fine too but if user have decided to use large/small thumbnails and have set it that via media settings then images inside widget will become large/small too. 

Why do you think that your approach would work better? I am not saying that mine is the best and one and only and would love to hear your opinion to decide which approach to use and why.

**Comment by qant** [comment]
Because if someone apply you theme after using another one like did.

In my post before, i am not using any miniatures at all, so with your theme when miniatures is not set, it shows gray square.

When i choice miniature for post it seems wrong:

1. It show BIG images not thumbnails.
2. the images is not line properly in div (because BIG image is not a square).

I don't have any screenshot to show you... because i already fix that.
I hope you understand what i mean. May be its because i used another theme before...

**Comment by qant** [comment]
here u have an image if i am not clear

![captura](https://cloud.githubusercontent.com/assets/951304/7681511/23dfbf92-fd71-11e4-9374-58b7ee39beee.JPG)

**Comment by puikinsh** [comment]
Ok, I see what you mean. That's why plugins [like this](https://wordpress.org/plugins/regenerate-thumbnails/) are so popular as they are meant to regenerate thumbnails when switching between themes or when changing featured image size via `functions.php`
