### ISSUE TITLE
Fix structured data errors 

### ISSUE THREAD

**Issue by LambdaSoft** [puikinsh/Sparkling#200]
The webmasters tool from Google notifies me of several errors in relation to structured data belonging to
this theme.
I fix them manually in my Wordpress website each time that I update this theme.
The errors are:  Missing "author" and "updated" in hatom (microformats.org)
Can you fix this errors, please?

Thanks in advance

**Comment by cristianraiber** [comment]
@giucu91 - can you please see this?

**Comment by giucu91** [comment]
Hello @LambdaSoft ,

Can you please create a pull request with your changes? We will include them in the next update.

Have a nice day,
George.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/39583991-fb7c52bc-4ef9-11e8-9bfb-3b1f9116602d.png)

**Comment by cristianraiber** [comment]
I have checked the theme's code and everything required is there. The screenshot above is taken from Google's Structured Data testing tool and as you can see, it shows 0 errors/warnings.

My best guess right now is that this is coming from a 3rd party plugin. Albeit, @akelsch provided a fix for showing the timestamp always (kudos) but the theme version I'm testing doesn't yet have that fix. 

🕊 All in all, if you could please tell me the exact plugins and settings you're using, I might be able to point you in the right direction of the culprit.

**Comment by akelsch** [comment]
I have used my own fix in functions.php for quite some time now. This is how it looks in Search Console:

![screenshot_20180503-170258 2](https://user-images.githubusercontent.com/28652314/39585244-961a3182-4ef4-11e8-8867-f021b8e2b5b0.png)

I never had a problem with the author tags though.

**Comment by cristianraiber** [comment]
@akelsch - would you please be so kind to provide me with your custom functions.php so I can actually see what's going on? I'm really having a hard time debugging this one.

**Comment by akelsch** [comment]
Yeah it should be the same as in my PR. I can post the exact code here later if you want me to.

**Comment by cristianraiber** [comment]
@joshin16 - make sure you update the theme to the latest version. @akelsch fix was implemented in May of this year.

Thanks,
Cristian.
