### ISSUE TITLE
Image slider for static pages

### ISSUE THREAD

**Issue by timaschew** [puikinsh/Sparkling#201]
First of all thank you for providing this cool theme!

I want to use the theme for static pages only, so I don't need and want to use blog posts.
But unfortunately I need to create multiple blog posts and assign a featured image in order to see the slider working.

Is there some workaround to not need blog posts to use the slider?
Or maybe do you have another similar theme which has a better focus on static pages?

**Comment by atkoehler** [comment]
@timaschew There is a workaround using plugins as the slider requires a category.

1) Create a slider category, and set slider to display that slider category.

2) Install the following plugin, "Post Tags and Categories for Pages"
https://wordpress.org/plugins/post-tags-and-categories-for-pages/

3) Edit various static pages, and set them in the slider category.

**Comment by cristianraiber** [comment]
❗️ @timaschew - This doesn't seem to be an actual theme bug but rather a feature request :) Such a feature might not be welcomed by all of the more than 60,000 users of this theme. As such, I believe @atkoehler's solution is a great one.

🕊 Marking this as closed since it's not an actual theme bug.
