### ISSUE TITLE
Date formating for popular post widget

### ISSUE THREAD

**Issue by puikinsh** [puikinsh/Sparkling#202]
There is an unnecessary space before the comma after the month name in the popular post widget as you can see in the screenshot below: 
<img width="308" alt="screenshot_2017-09-12_13_54_48" src="https://user-images.githubusercontent.com/3451398/30322421-199b3c1c-97c2-11e7-8ae5-d8e80783770a.png">

Code: 
https://github.com/puikinsh/Sparkling/blob/7b97a17df4ae9b716887b6e07496917d2bfd60f6/inc/widgets/class-sparkling-popular-posts.php#L90

Also, wouldn't it be better to use the default `get_the_date()` to make a use of WordPress option to change the date via Settings - General? Because changing the date for posts widget no longer will match. It is just an idea.

**Comment by cristianraiber** [comment]
@giucu91 - this is most likely old code from the Sparkling theme, but @puikinsh is right. 

We should be using `get_the_date( get_option('date_format') )`
