### ISSUE TITLE
Minified javascript files are larger than non minified files

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/Sparkling#203]
Minified javascript files are larger than non minified files as displayed below instead it should be opposite.

assets/js/vendor/bootstrap.js – 69KB
assets/js/vendor/bootstrap.min.js 434KB

Related Topic:
https://colorlib.com/wp/forums/topic/large-minified-js-in-theme/

**Comment by cristianraiber** [comment]
@vinoddalvi - I'll have a look at this :)
