### ISSUE TITLE
Add a social icon for Docker Hub

### ISSUE THREAD

**Issue by MatthiasLohr** [puikinsh/Sparkling#204]
Hey,

could you please add a social icon for docker hub? Thank you very much!

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Maybe also useful: https://github.com/FortAwesome/Font-Awesome/issues/3316

But i think waiting for FontAwesome 5.0.0 release would be really annoying...

**Comment by MatthiasLohr** [comment]
Anything new here?

**Comment by cristianraiber** [comment]
@MatthiasLohr - I'll look into updating FA to v5

**Comment by MatthiasLohr** [comment]
In the meantime it has also been released :P
