### ISSUE TITLE
Add a social icon for StackOverflow

### ISSUE THREAD

**Issue by MatthiasLohr** [puikinsh/Sparkling#205]
Hello,

it would be really nice to have a social icon for StackOverflow, for linking to developer stories (e.g. https://stackoverflow.com/story/matthias.lohr).

Thanks in advance!

Best regards
Matthias Lohr

**Comment by MatthiasLohr** [comment]
Anything new here?

**Comment by cristianraiber** [comment]
@MatthiasLohr - please see this: https://github.com/puikinsh/Sparkling/pull/206
