### ISSUE TITLE
Bootstrap modal does not open

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/Sparkling#207]
Related Topic:

https://wordpress.org/support/topic/bootstrap-modal-open/#post-9623287

**Comment by vinoddalvi** [comment]
Any updates here?

Other user is asking for the same.

**Comment by cristianraiber** [comment]
@vinoddalvi - I'll look into this

**Comment by cristianraiber** [comment]
@vinoddalvi - this works just fine with the Bootstrap Modal code provided by the user here:https://www.w3schools.com/bootstrap/bootstrap_modal.asp (linked in your ticket as well).

❗️ Please make sure to test tickets you report, before actually reporting them. This way you will make sure we don't both waste time on the same issue.


💯 Screenshot from my local machine, where modal is showing up

![image](https://user-images.githubusercontent.com/7841556/39583163-26163a80-4ef8-11e8-83cb-2b54c53915fe.png)
