### ISSUE TITLE
drop-down menu issue on desktop

### ISSUE THREAD

**Issue by mplusb** [puikinsh/Sparkling#211]
You should only be allow to click on the drop-down arrow on mobile. 
If you click on it on desktop it remains open
![bug](https://user-images.githubusercontent.com/26008574/35566289-88a296f8-05c9-11e8-9995-c474f21c3470.png)

**Comment by nodarik** [comment]
related to this or same:
https://github.com/puikinsh/Sparkling/issues/208

**Comment by cristianraiber** [comment]
Closing as it's a duplicate of #208.
