### ISSUE TITLE
Tables in blog posts are not responsive

### ISSUE THREAD

**Issue by ErikThiart** [puikinsh/Sparkling#213]
Works fine on the desktop, but on mobile, the table is not responsive.

![2018-03-01_21-00-13](https://user-images.githubusercontent.com/9626641/36863941-c7abbe92-1d93-11e8-8948-702d3a2d9b9f.jpg)

Mobile View
![2018-03-01_21-01-00](https://user-images.githubusercontent.com/9626641/36863950-cfb9a16c-1d93-11e8-90f5-937729be4a31.jpg)

**Comment by cristianraiber** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/7841556/39582919-a4f986c8-4ef7-11e8-90f0-35b47ffd356e.png">

**Comment by cristianraiber** [comment]
@ErikThiart - Tables are responsive in BS3 (Bootstrap 3). However, there's a small trick required to make it work (that's taken officially from the BS3 documentation), and that is - you have to wrap the whole table in a div with the class of `responsive-table`. That's it :) 

:dove: This is not a bug, but rather a mis-usage of BS3. Don't worry about it though, the only thing you need to do now is wrap your `table` in a `<div class="table-responsive">` and everything will be working properly :) 

Thanks,
Cristian.
