### ISSUE TITLE
Fix releases page

### ISSUE THREAD

**Issue by MatthiasLohr** [puikinsh/Sparkling#217]
Hello,

there is some strange tag and release named ```untagged-4cc5d1eaacad822d0d14``` (see https://github.com/puikinsh/Sparkling/releases). I think that happend unintentionally. Maybe you should fix that.

Best regards
Matthias

**Comment by cristianraiber** [comment]
@MatthiasLohr - we have TravisCI setup to automatically create releases from pull requests. We, mistakenly, merged a 3rd party pull request and as such, TravisCI did what he was trained to do: tag & release :) 

🕊  Nonetheless, I've gone ahead and deleted that tag from the releases page. Unfortunately, GitHub doesn't allow us to fully delete releases from that page, the most we can do is delete the release information.

**Comment by MatthiasLohr** [comment]
You can delete a tag as well as the release at GitHub:
  * ```git push origin :refs/tags/12345``` (https://gist.github.com/mobilemind/7883996)
  * https://help.github.com/articles/editing-and-deleting-releases/#deleting-a-release

I would also recommend that you change the configuration of Travis CI. Never accepting a pull request makes you more work and is not satisfactory for Contributor. You could configure Travis CI to create a release whenever you manually create a tag. Then you have full control over the name of the release, pull requests can be accepted and releases are always created exactly when they should: If they are named manually over a tag.
