### ISSUE TITLE
feed social icon stopped working after update to 2.4.0

### ISSUE THREAD

**Issue by MatthiasLohr** [puikinsh/Sparkling#219]
Hello,

the social icon for feeds stopped working after the update to 2.4.0. See https://mlohr.com for an example (bottom).

Best regards
Matthias

**Comment by cristianraiber** [comment]
@MatthiasLohr - I'm on it :)

**Comment by MatthiasLohr** [comment]
Is that a bug in FontAwesome?

**Comment by cristianraiber** [comment]
Most likely, yep :) The font-family: "Font Awesome 5 Free" already has a font-weight of 900 defined in the font's CSS stylesheet. Nonetheless, it looks like it needs to have one as well when adding certain icons.

For all the other icons, it wasn't needed.

**Comment by cristianraiber** [comment]
Just pushed a commit to address this issue.

**Comment by MatthiasLohr** [comment]
Could you also try "solid" as value? See https://fontawesome.com/icons/rss?style=solid (especially the GET variable ```style=solid```).

Also you could test this: https://fontawesome.com/icons/rss-square?style=solid

**Comment by cristianraiber** [comment]
@MatthiasLohr - that GET parameter is only for FontAwesome's website :) It's there to help them distinguish between the other font styles. It's not something that can help/work in our situation.

**Comment by MatthiasLohr** [comment]
Ah sorry... my fault. I mixed up the terms ```solid``` and ```bold```. I tried it by myself, ```font-weight: bold;``` works also. I always would recommend to use keywords instead of numbers.

**Comment by cristianraiber** [comment]
@MatthiasLohr - different browsers/browser versions interpret the term `solid` differently. Using numeric values is best in this case :)

**Comment by MatthiasLohr** [comment]
@puikinsh, could you please upload the update to wordpress? Thanks!
