### ISSUE TITLE
Category Icon not display

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [puikinsh/Sparkling#221]
Hi.
I updated this theme Sparkling.
Category icon does not appear.
Do I forget to set  @something?

![180509-0001](https://user-images.githubusercontent.com/5963990/39814259-8ad5e314-53ce-11e8-89d3-f772af845c88.png)

**Comment by YoshinoriKobayashi** [comment]
@cristianraiber Thank you!
I am waiting for the next update :-)

**Comment by puikinsh** [comment]
While you are there, please make sure to fix FA icons for all the widgets, slider and everything else.
