### ISSUE TITLE
Broken Font Awesome 4 icons

### ISSUE THREAD

**Issue by akelsch** [puikinsh/Sparkling#223]
A list of icons I've found non working after the upgrade to 2.4.2:

- fa-comment-o
- fa-folder-open-o
- fa-pencil-square-o

Possible replacements:

- [fa-comments](https://fontawesome.com/icons/comments?style=regular)
- [fa-folder-open](https://fontawesome.com/icons/folder-open?style=regular)
- [fa-edit](https://fontawesome.com/icons/edit?style=regular)

**Comment by cristianraiber** [comment]
@akelsch - could you please let me know where you found these icons missing? If they're for the widgets in the sidebar, those were just fixed in 2.4.2 and I would recommend clearing your cache :)

**Comment by akelsch** [comment]
They are used in article summaries on the home page and article headers (both in entry-meta class).

Make sure you don't have a second source of Font Awesome icons installed as I found a plugin that includes FA 4.7 on my website.

**Comment by cristianraiber** [comment]
@akelsch - Thanks for pointing this out. I'll check again for broken FA icons. I'm so glad FA5 decided to change most of their icons :/

**Comment by cristianraiber** [comment]
@akelsch - I've just pushed out an update; v2.4.3 (should hit the w.org repo soon) should address this issue. Hopefully, I didn't miss anymore of those pesky FA5 icons :/
