### ISSUE TITLE
Custom favicon from HTTPS

### ISSUE THREAD

**Issue by 7starsone** [puikinsh/Sparkling#25]
Hello,
please can you fix on extras.php
``` 
echo '<link rel="shortcut icon" type="image/x-icon" href="' . of_get_option( 'custom_favicon' ) . '" />'. "\n";
```
to load the favicon from https (if needed) or let me know how to edit... I know that i can directly write // and the url or relative path but I think that's better if you fix it from scratch...
thank you very much

**Comment by puikinsh** [comment]
There is no error in theme and Sparkling theme does use `https` and `http` properly. However, you selected your favicon image before you switched to SSL/TLS which means that it is still saved as  `http` in Theme Options. Just add this image again or just replace `http` with `https` in Favicon URL field and save changes. 

Let me know if this helps.

**Comment by 7starsone** [comment]
the error is there, 'cause you don't expect that only some pages need https
so, or you could delete ***http:*** from the final url or you make a function which considers whether http or https...

**Comment by puikinsh** [comment]
In that case you will have to edit this URL field manually to leave only  `// `. Media upload us handled by WordPress itself and the only solution would be to use some hacky `str_replace` or some other alternative but I don't think it is worth the hassle. 

If you have a better idea, please let me know and I will look into it.

**Comment by 7starsone** [comment]
you could do
```
function isSecure() {
  return
    (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
    || $_SERVER['SERVER_PORT'] == 443;
}
function sparkling_add_favicon() {
  if ( of_get_option( 'custom_favicon' ) &&  isSecure()) {
    $urlhttp = of_get_option( 'custom_favicon' );
    $urlhttps = preg_replace("/^http:/i", "https:", $urlhttp);
    echo '<link rel="shortcut icon" type="image/x-icon" href="' . $urlhttps . '" />'. "\n";
  } elseif (of_get_option( 'custom_favicon' )) {
    echo '<link rel="shortcut icon" type="image/x-icon" href="' . of_get_option( 'custom_favicon' ) . '" />'. "\n";   
  }
}
```
on sparkling_add_favicon if the first if is true ;-) then it goes fine.
I didn't try but it should work... let me know
bye

**Comment by puikinsh** [comment]
Theme now uses WordPress built it Site Icon function introduced in WP 4.3 therefore this issue is no longer relevant.
