### ISSUE TITLE
Category page is not functioning

### ISSUE THREAD

**Issue by ajai-sandy** [puikinsh/Sparkling#26]
Hi ,
  I tried your theme and its awesome, the problem that I facing now is I created a category and added a post in it, when I select the category from the navbar or in sidebar am redirected to the 404 error page.
Thanks in advance.

![untitled-1](https://cloud.githubusercontent.com/assets/6812847/7853679/37730ef4-052f-11e5-99da-2924f54ba251.jpg)

**Comment by puikinsh** [comment]
Make sure that .htaccess rewrite rules are working properly. I see that category "Watches" does have one post so it shouldn't return a blank page as long as permalinks are working properly and it appears that they are not working.

**Comment by ajai-sandy** [comment]
Hi @puikinsh thank you for the solution, the problem was with the permalinks now its working good..
Pls keep up the good work of creating an awesome theme and thanks for clearing my problem.
