### ISSUE TITLE
Issue with pagination buttons on Sparkling theme single image attachment pages

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#30]
On the attachment pages, the buttons no longer appear as buttons, but as horizontal bars.

Find more information about the issue in the following topic.

https://colorlib.com/wp/forums/topic/issue-with-buttons-on-sparkling-theme-attachment-pages/#post-24010

**Comment by puikinsh** [comment]
Thank you for reporting it! 

I have since fixed it and you can see it https://github.com/puikinsh/Sparkling/commit/cca57c9a52d5261b0b5cec6fc38ee8071fb6a663
