### ISSUE TITLE
Featured slider doesn't show text in mobile view

### ISSUE THREAD

**Issue by mattzuba** [puikinsh/Sparkling#31]
When viewing my site via mobile, I see the featured slider images, but there is no text like in the desktop view.  Example: https://www.thefitcoder.net

**Comment by puikinsh** [comment]
It is expected behavior because slider becomes too small on mobile and slider caption will cover the entire slider + post content + menu and that's not something you want to see. 

For your website something like this could work but it won't work for most other websites:

```
@media (max-width: 768px) {
  .flex-caption {
    display: block;
    bottom: 10px;
  } 
  .flex-caption h2 {
    font-size: 14px;
    padding: 5px;
  }
  .flex-caption .excerpt {
    font-size: 11px;
    padding: 5px;
  }
}
```
