### ISSUE TITLE
WordPress Menu not displaying correct on IOS

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#32]
When we press 2 times on the same link the sub items will turn blank.

Find information about the issue and solution on the following thread.

https://colorlib.com/wp/forums/topic/menu-not-displaying-correct-on-ios/

**Comment by puikinsh** [comment]
This is now fixed with some extra styling improvements. Please see for more info https://github.com/puikinsh/Sparkling/commit/eb4c2511df56a7adf2a3b2c9e995baaa23ac23f2
