### ISSUE TITLE
Search Form Translation

### ISSUE THREAD

**Issue by erayaydin** [puikinsh/Sparkling#35]
Hello,

My searchform doesn't translate to Turkish. Its look "Search...". Its should "Arama...". In tr_TR.po/tr_TR.mo file there is translate exists but not effect to searchform.php

Other fields ok with Turkish.

**Comment by erayaydin** [comment]
> that commit not for this issue, my fail sorry.

**searchform.php**, `esc_attr_x` to `esc_attr_e` fixed my problem but I think its *dirty way* for fix.

**Comment by puikinsh** [comment]
I would appreciate if you could give updated theme version a try. It should fix problems with "Search..." translation. 

Thank you for your other commits! I really appreciate your time and effort!
