### ISSUE TITLE
Home page to loong...

### ISSUE THREAD

**Issue by baxandrei** [puikinsh/Sparkling#42]
How i can limitate lastet post to a number of words?...

**Comment by baxandrei** [comment]
Here is website. http://blog.eftimieandrei.tk/ i wanna to limitate the height of items.

**Comment by baxandrei** [comment]
I found the solution:

FILE: content.php 

remove:

				<?php
				if ( get_theme_mod( 'sparkling_excerpts' ) == 1 ) :
					the_excerpt();
				else :
					the_content();
				endif;
				 ?>

and replace with:

				<?php the_excerpt(); ?>

**Comment by puikinsh** [comment]
There is an options under Appearance >> Customize >> Content Options. Of course it no longer works as you removed this code from content.php but it were a much easier option that trying to code something.

**Comment by baxandrei** [comment]
Thanx, it is more easy :)
