### ISSUE TITLE
Password protected page renders HTML tags as it is

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#49]
See on the following Password protected page the p tag is rendered

https://colorlib.com/sparkling/template-password-protected/

**Comment by FreeWPTP** [comment]
Provided the solution in the following reply to fix the issue.

https://colorlib.com/wp/forums/topic/password-protected-page-not-rendering-html/#post-30011

**Comment by ptt-homme** [comment]
Or just update your theme as I provided a PR #40.
