### ISSUE TITLE
Change the Google+ icon with the new G+ icon in the social share icons

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#53]
Find the related thread here https://colorlib.com/wp/forums/topic/follow-us-g-icon/

**Comment by puikinsh** [comment]
This theme uses Font Awesome font icons and the new G+ icon is not yet available. We will update theme once this icon will be available on Font Awesome.

**Comment by FreeWPTP** [comment]
Font Awesome Reference : https://github.com/FortAwesome/Font-Awesome/issues/7357
