### ISSUE TITLE
Resolve fuzzy translation in the file fr_FR.po

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#54]
Related thread https://colorlib.com/wp/forums/topic/search-bar-translation/#post-33617

**Comment by puikinsh** [comment]
This problem is solved on https://github.com/puikinsh/Sparkling/pull/67

**Comment by Angristan** [comment]
Bug fix is not included is 2.0.1 ?

**Comment by puikinsh** [comment]
@Angristan It was fixed in 2.1.0 and not 2.0.1 but this version is not yet available on WordPress.org. It will be available shortly.
