### ISSUE TITLE
Child theme home page layout gets messed up

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#56]
The Sparkling them is working fine but when we use child theme of Sparkling theme then the home page layout gets messed up regardless whether the slider is enabled or not as shown in the attached screenshot.
![screenshot 1](https://cloud.githubusercontent.com/assets/11946142/10685824/05b63bc2-797c-11e5-9c3e-7f5ba0e47e97.png)

The issue gets resolved when i use the following CSS code.

```
.row.pull-left {
  max-width: 100%;
}
```

**Comment by FreeWPTP** [comment]
It was the cache issue.

**Comment by puikinsh** [comment]
Switching layout settings via Appearance >> Sparkling Options >> Layout Options to "Left Sidebar" or other layout and saving changes and then going back to original layout options will solve this problem. It is a cache issue due to newly introduced layout management settings.
