### ISSUE TITLE
Create a fallback for the deprecated function sparkling_social

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#57]
It seems in the latest theme version we have replaced the function sparkling_social with the function sparkling_social_icons so it's affecting the members who have overwritten the footer.php file in their child theme.

We should also add the fallback of the function sparkling_social in the theme functions.php file which will call the function sparkling_social_icons as following.

```
function sparkling_social(){

	 if( of_get_option('footer_social') ) { 
	 	sparkling_social_icons();
	 }
}
```

**Comment by puikinsh** [comment]
I have implemented in on this commit: https://github.com/puikinsh/Sparkling/commit/2c7c28bfef6923829bbedc3dcb0646cc55211b92

Please check and let me know if everything is correct.

**Comment by FreeWPTP** [comment]
Yes it seems correct.
