### ISSUE TITLE
Feature Request - For SEO purpose there should be only one H1 tag on the page

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#60]
In the default Twenty Fifteen theme on the home page the site name is wrapped in H1 tags and the posts listed on the home page is wrapped in H2 tags  whereas in the Sparkling theme site title is wrapped in span tag and the posts listed on the home page is wrapped in H1 tags.

Related Topic : https://wordpress.org/support/topic/homepage-title-is-not?replies=1

**Comment by puikinsh** [comment]
Fixed on #68
