### ISSUE TITLE
"Top nav item hover color" option overrides .entry-title a:hover

### ISSUE THREAD

**Issue by michaelck** [puikinsh/Sparkling#71]
When using Customizr to set the "Top nav item hover color" .entry-title a:hover also takes on this style. It may make sense to allow .entry-title a:hover to instead take on the general "Link:hover color". Otherwise you may run into situations where the hover color, designed to look pleasing against the navbar does not work well with the content area background-color (example: using default colors, set "Top nav item hover color" to a very light color or white, and hover over a post title).

**Comment by michaelck** [comment]
Proposed solution with Pull Request #72

**Comment by puikinsh** [comment]
Merged on https://github.com/puikinsh/Sparkling/pull/75

Thank you for your contribution!

**Comment by michaelck** [comment]
@puikinsh Ahh now I see. Great! :+1: 

Happy to continue contributing if you're open to it.
