### ISSUE TITLE
A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#73]
For the meta element http-equiv attribute, the W3C validation is displaying the error as shown in the attached screenshot.

![screenshot 21](https://cloud.githubusercontent.com/assets/11946142/11494186/0999a24c-9826-11e5-9e17-1911987c4909.png)

Related threads and solution :
https://colorlib.com/wp/forums/topic/meta-tags-causing-issues-with-w3c-validation/#post-36852
http://stackoverflow.com/a/28110527/1287548

**Comment by puikinsh** [comment]
Fixed on https://github.com/puikinsh/Sparkling/pull/75
