### ISSUE TITLE
 Stray end tag div in the theme

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Sparkling#74]
In the theme there is not opened end div tag which is causing the issue as displayed in the attached screenshots.

![screenshot 22](https://cloud.githubusercontent.com/assets/11946142/11494481/ccc3d84e-9828-11e5-87e8-c0d1f213e2d5.png)

![screenshot 23](https://cloud.githubusercontent.com/assets/11946142/11494483/d1ea19d2-9828-11e5-8e69-5a405a7fc2db.png)

I have tested it on my test site and found if i remove the following div tag from the theme footer.php file then it seems the issue is resolved.

```
</div><!-- close .*-inner (main-content or sidebar, depending if sidebar is used) -->
```

Related thread :

https://colorlib.com/wp/forums/topic/w3c-validation-error/

**Comment by puikinsh** [comment]
Fixed on https://github.com/puikinsh/Sparkling/pull/75
